codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: false
      tests:
        target: 100%
        paths:
          - "tests/"
      app:
        threshold: 5%
        paths:
          - "!tests/"
    patch: false
    changes: false
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
ignore:
  - tests/*
  - docs/*
